// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
function createSupabaseClient() {
  const SUPABASE_URL = "https://fumxdmvjvmqfvrrevwkw.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_0zHXUpIEJlQuCBujVAyaPw_qJLI9jxm";

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}
export const supabase=createSupabaseClient()